// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkW_trkZ2dIiyQmH6q4cCJ5A5chIp_ppg',
    appId: '1:7070771249:web:065bbe5b61618455634d10',
    messagingSenderId: '7070771249',
    projectId: 'mpc-wallet-c6f6e',
    authDomain: 'mpc-wallet-c6f6e.firebaseapp.com',
    storageBucket: 'mpc-wallet-c6f6e.appspot.com',
    measurementId: 'G-MW7BPEXLNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXrVstHw1f-uqpIFnXSpoqn7uHJHBHbLk',
    appId: '1:7070771249:android:47860ed437af0fe0634d10',
    messagingSenderId: '7070771249',
    projectId: 'mpc-wallet-c6f6e',
    storageBucket: 'mpc-wallet-c6f6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPJo9_mejRRg_Q4X56V_l195FmwfysjIc',
    appId: '1:7070771249:ios:b6107bb6b52c9b69634d10',
    messagingSenderId: '7070771249',
    projectId: 'mpc-wallet-c6f6e',
    storageBucket: 'mpc-wallet-c6f6e.appspot.com',
    iosBundleId: 'com.example.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPJo9_mejRRg_Q4X56V_l195FmwfysjIc',
    appId: '1:7070771249:ios:2546a4011402fe3a634d10',
    messagingSenderId: '7070771249',
    projectId: 'mpc-wallet-c6f6e',
    storageBucket: 'mpc-wallet-c6f6e.appspot.com',
    iosBundleId: 'com.example.wallet.RunnerTests',
  );
}
